server:
  port: 8080

springdoc:
  swagger-ui:
    operationsSorter: method
    display-request-duration: true
    
caching:
  refresh:
    activate: false
    timeRefreshCache: 5000

spring:  
  datasource:
    url: jdbc:postgresql://localhost:5438/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
